version: "3.8"
services:
    quiztrovedb:
        image: mysql:5.7
        restart: always
        container_name: db-mysql
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: testuser
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
    database-explorer:
        image: phpmyadmin
        restart: always
        ports:
            - 8037:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: quiztrovedb
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: secret